name: Nightly Build

on:
  push:
  pull_request:
  schedule:
  - cron: '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Cache last built versions
      id: cache-build-versions
      uses: actions/cache@v4
      with:
        path: |
          last_master
          last_version
        key: ${{ runner.os }}-primes

    - name: Install curl and jq
      run: |
        sudo apt-get install curl jq -y

    - name: Run build script
      run: |
        bash -x build.sh